version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: hotel_db
    restart: unless-stopped
    environment:
      # CRUCIAL: Configura la contraseña del usuario root (vacía)
      MYSQL_ROOT_PASSWORD: "" 
      # CRUCIAL: Permite explícitamente la contraseña vacía para el root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
      # Configura el nombre de la DB a crear
      MYSQL_DATABASE: gestion_hotelera
    ports:
      - "3307:3306" # Opcional: para conectar un cliente externo
    volumes:
      # CRUCIAL: Ejecuta tu script SQL al levantar el contenedor por primera vez
      - ./db_init/Hotel_BD.sql:/docker-entrypoint-initdb.d/Hotel_BD.sql
      - db_data:/var/lib/mysql # Persistencia de datos para la DB
    networks:
      - hotel-net

  web:
    build: ./web # Construye la imagen usando el Dockerfile en la carpeta 'web'
    container_name: hotel_web
    restart: unless-stopped
    ports:
      - "3310:80" # Mapea 3310 (local) a 80 (contenedor)
    environment:
      # VARIABLES QUE LA APP UTILIZA PARA CONECTARSE A LA DB
      DB_HOST: db                    # ¡El host es el nombre del servicio 'db'!
      DB_PORT: 3306
      DB_NAME: gestion_hotelera
      DB_USER: root
      DB_PASS: "" # Debe coincidir con la de la DB
    depends_on:
      - db # Asegura que la DB inicie antes que la Web
    networks:
      - hotel-net

networks:
  hotel-net:
    driver: bridge

volumes:
  db_data: # Define el volumen de persistencia
